//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Conection
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustomerEvent
    {
        public int customer_id { get; set; }
        public int event_id { get; set; }
        public bool suscribed_to_alerts { get; set; }
        public System.DateTime create_time { get; set; }
        public System.DateTime update_time { get; set; }
    
        public virtual tblCustomer tblCustomer { get; set; }
        public virtual tblEvent tblEvent { get; set; }
    }
}
