//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Conection
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEventComment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblEventComment()
        {
            this.tblEventComment1 = new HashSet<tblEventComment>();
        }
    
        public int comment_id { get; set; }
        public int event_id { get; set; }
        public int customer_id { get; set; }
        public string message_content { get; set; }
        public System.DateTime create_time { get; set; }
        public System.DateTime update_time { get; set; }
        public int in_reply_to_comment { get; set; }
    
        public virtual tblCustomer tblCustomer { get; set; }
        public virtual tblEvent tblEvent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEventComment> tblEventComment1 { get; set; }
        public virtual tblEventComment tblEventComment2 { get; set; }
    }
}
