//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Conection
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEvent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblEvent()
        {
            this.tblCustomerEvent = new HashSet<tblCustomerEvent>();
            this.tblEventComment = new HashSet<tblEventComment>();
            this.tblPublicity = new HashSet<tblPublicity>();
            this.tblArtist = new HashSet<tblArtist>();
            this.tblGenre = new HashSet<tblGenre>();
        }
    
        public int event_id { get; set; }
        public string name { get; set; }
        public string geographical_location { get; set; }
        public int city_id { get; set; }
        public System.DateTime event_date { get; set; }
        public int create_by { get; set; }
        public System.DateTime create_time { get; set; }
        public System.DateTime update_time { get; set; }
        public string event_source_site_page { get; set; }
        public int culturaljob_task_id { get; set; }
        public string tags { get; set; }
        public bool requested_by_artist { get; set; }
        public string EventImagePath { get; set; }
    
        public virtual tblCity tblCity { get; set; }
        public virtual tblCulturalJobTasks tblCulturalJobTasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCustomerEvent> tblCustomerEvent { get; set; }
        public virtual tblUser tblUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEventComment> tblEventComment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPublicity> tblPublicity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblArtist> tblArtist { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblGenre> tblGenre { get; set; }
    }
}
