//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Conection
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPublicity
    {
        public int ad_id { get; set; }
        public string ad_title { get; set; }
        public int create_by { get; set; }
        public System.DateTime create_time { get; set; }
        public int update_by { get; set; }
        public System.DateTime update_time { get; set; }
        public System.DateTime start_period { get; set; }
        public System.DateTime end_period { get; set; }
        public int cant_of_follows { get; set; }
        public int related_event { get; set; }
        public bool requested_by_artist { get; set; }
        public Nullable<int> artist_id { get; set; }
    
        public virtual tblArtist tblArtist { get; set; }
        public virtual tblEvent tblEvent { get; set; }
    }
}
